[package]
name = "pidjezdy"
description = "Actionable PID departure information"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chrono.workspace = true
clap.workspace = true
directories.workspace = true
pidjezdy-core = { path = "../pidjezdy-core" }
pidjezdy-pid = { path = "../pidjezdy-pid" }
thiserror.workspace = true

[dev-dependencies]
tempfile = "3.23.0"
url.workspace = true

[lints]
workspace = true
