[package]
name = "pidjezdy-pid"
description = "PID API adapter for pidjezdy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chrono.workspace = true
flate2.workspace = true
pidjezdy-core = { path = "../pidjezdy-core" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true

[lints]
workspace = true
